### ISSUE TITLE
Update: About Page

### ISSUE THREAD

**Issue by wilpola** [wilpola/rock-paper-scissors-react#2]
# Write the "About" page

> The about page will contain all the necessary information about the development process, what were some things that I struggled with along with explanations for how I overcame those hurdles. This page will also contain all the necessary information about the library choices as well as the reasoning behind including them.

## TODO:
- [ ] Design and Develop the layout for the "About" page
- [ ] Write out the content of the page
- [ ] Make the page responsive
