### ISSUE TITLE
feat: Redux

### ISSUE THREAD

**Issue by wilpola** [wilpola/rock-paper-scissors-react#3]
## Why?
It would be too much to fetch the same data every single time the user goes to the about page and then comes back. It is a no-brainer to bring in redux to avoid the need for fetching and updating the state every time the DOM updates.

## TODO:

- [ ] import the library
- [ ] Create the Store
- [ ] Implement redux
- [ ] Test it out
